# Generated by Django 6.0.3 on 2026-03-29 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=5)),
                ('translated_title', models.CharField(max_length=500)),
                ('translated_content', models.TextField()),
                ('translated_summary', models.TextField(blank=True)),
                ('quality_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.article')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source_article', 'language')},
            },
        ),
    ]
