# Generated by Django 6.0.3 on 2026-03-29 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list)),
                ('profile_extracted', models.JSONField(blank=True, default=dict)),
                ('products_recommended', models.JSONField(blank=True, default=list)),
                ('session_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('marketplace', 'Marketplace'), ('support', 'Support')], default='onboarding', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
