# Generated by Django 6.0.3 on 2026-03-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_categories', models.JSONField(default=list)),
                ('preferred_sources', models.JSONField(default=list)),
                ('blocked_topics', models.JSONField(default=list)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('daily_digest_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
