# Generated by Django 6.0.3 on 2026-03-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navigator', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='source_articles',
            field=models.ManyToManyField(blank=True, related_name='briefings', to='news.article'),
        ),
    ]
