# Generated by Django 6.0.3 on 2026-03-29 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('reading_level', models.CharField(blank=True, max_length=20)),
                ('reading_time_minutes', models.IntegerField(default=5)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_breaking', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
    ]
