# Generated by Django 6.0.3 on 2026-03-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source_name'], name='news_articl_source__79ec8c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_processed'], name='news_articl_is_proc_d9e06d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_trending'], name='news_articl_is_tren_184d6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readinghistory',
            unique_together={('user', 'article')},
        ),
    ]
